GOODEGGSTAR1 = "Good Egg 1: Dino Piranha"
GOODEGGSTAR2 = "Good Egg 2: A Snack of Cosmic Proportions"
GOODEGGSTAR3 = "Good Egg 3: King Kaliente's Battle Fleet"
GOODEGGSTAR4 = "Good Egg Comet: Dino Piranha Speed Run"
GOODEGGSTAR5 = "Good Egg Purple Coins: Purple Coin Omelet"
GOODEGGSTAR6 = "Good Egg Luigi: Luigi on the Roof"

HONEYHIVESTAR1 = "Honeyhive 1: Bee Mario Takes Flight"
HONEYHIVESTAR2 = "Honeyhive 2: Trouble on the Tower"
HONEYHIVESTAR3 = "Honeyhive 3: Big Bad Bugaboom"
HONEYHIVESTAR4 = "Honeyhive Comet: Honeyhive Cosmic Mario Race"
HONEYHIVESTAR5 = "Honeyhive Purple Coins: The Honeyhive's Purple Coins"
HONEYHIVESTAR6 = "Honeyhive Luigi: Luigi in the Honeyhive Kingdom"

LOOPDEELOOPSTAR = "Loopdeeloop: Surfing 101"
FLIPSWITCHSTAR = "Flipswitch: Painting the Planet Yellow"
ROLLINGGREENSTAR = "Rolling Green: Rolling in the Clouds"
HURRYSCURRYSTAR = "Hurry-Scurry: Shrinking Satellite"
BUBBLEBREEZESTAR = "Bubble Breeze: Through the Poison Swamp"
HONEYCLIMBSTAR = "Honeyclimb: Scaling the Sticky Wall"
BUOYBASESTAR1 = "Buoy Base: The Floating Fortress"
BUOYBASESTAR2 = "Buoy Base Secret: The Secret of Buoy Base"
GATEWAYSTAR1 = "Gateway: Grand Star Rescue"
BONEFINSTAR = "Bonefin: Kingfin's Fearsome Waters"
MATTERSPLATTERSTAR = "Matter Splatter: Watch Your Step"
ROLLINGGIZMOSTAR = "Rolling Gizmo: Gizmos, Gears, and Gadgets"
LOOPDEESWOOPSTAR = "Loopdeeswoop: The Galaxy's Greatest Wave"
BUBBLEBLASTSTAR = "Bubble Blast: The Electric Labyrinth"

SPACEJUNKSTAR1 = "Space Junk 1: Pull Star Path"
SPACEJUNKSTAR2 = "Space Junk 2: Kamella's Airship Attack"
SPACEJUNKSTAR3 = "Space Junk 3: Tarantox's Tangled Web"
SPACEJUNKSTAR6 = "Space Junk Secret: Yoshi's Unexpected Apparence"
SPACEJUNKSTAR4 = "Space Junk Comet: Pull Star Path Speed Run"

BATTLEROCKSTAR1 = "Battle Rock 1: Battlerock Barrage"
BATTLEROCKSTAR2 = "Battle Rock 2: Breaking into the Battlerock"
BATTLEROCKSTAR3 = "Battle Rock 3: Topmaniac and Topman Tribe"
BATTLEROCKSTAR6 = "Battle Rock Secret: Battlerock's Garbage Dump"
BATTLEROCKSTAR4 = "Battle Rock Comet: Topmanic's Dardevil Run"
BATTLEROCKSTAR7 = "Battle Rock Luigi: Luigi under the Saucer"

BEACHBOWLSTAR1 = "Beach Bowl 1: Sunken Treasure"
BEACHBOWLSTAR2 = "Beach Bowl 2: Passing the Swim Test"
BEACHBOWLSTAR3 = "Beach Bowl 3: The Secret Undersea Cavern"
BEACHBOWLSTAR4 = "Beach Bowl Comet: Fast Foes on the Cyclone Stone"
BEACHBOWLSTAR6 = "Beach Bowl Secret: Wall Jumping Up Waterfalls"

GUSTYGARDENSTAR1 = "Gusty Garden 1: Bunnies in the Wind"
GUSTYGARDENSTAR2 = "Gusty Garden 2: The Dirty Tricks of Major Burrows"
GUSTYGARDENSTAR3 = "Gusty Garden 3: Gusty Garden's Gravity Scramble"
GUSTYGARDENSTAR4 = "Gusty Garden Comet: Major Burrows's Daredevil Run"
GUSTYGARDENSTAR6 = "Gusty Garden Secret: The Golden Chomp"

FREEZEFLAMESTAR1 = "Freezeflame 1: The Frozen Peak of Baron Brr"
FREEZEFLAMESTAR2 = "Freezeflame 2: Freezeflame's Blistering Coore"
FREEZEFLAMESTAR3 = "Freezeflame 3: Hot and Cold Collide"
FREEZEFLAMESTAR6 = "Freezeflame Secret: Conquring the Summit"
FREEZEFLAMESTAR4 = "Freezeflame Comet: Frosty Cosmic Mario Race"

DUSTYDUNESTAR1 = "Dusty Dune 1: Soaring on the Desert Winds"
DUSTYDUNESTAR2 = "Dusty Dune 2: Blasting through the Sand"
DUSTYDUNESTAR3 = "Dusty Dune 3: Sunbaked Sand Castle"
DUSTYDUNESTAR4 = "Dusty Dune Comet: Sandblast Speed Run"
DUSTYDUNESTAR6 = "Dusty Dune Secret: Bullet Bill on Your Back"
DUSTYDUNESTAR7 = "Dusty Dune Green: Treasure of the Pyramid"

GHOSTLYSTAR1 = "Ghostly 1: Luigi and the Haunted Mansion"
GHOSTLYSTAR2 = "Ghostly 2: A Very Spooky Spirit"
GHOSTLYSTAR3 = "Ghostly 3: Beware of Bouldergeist"
GHOSTLYSTAR4 = "Ghostly Comet: Bouldergeist's Daredevil Run"
GHOSTLYSTAR6 = "Ghostly Secret: Matter Splatter Mansion"

GOLDLEAFSTAR1 = "Gold Leaf 1: Star Bunnies on the Hunt"
GOLDLEAFSTAR2 = "Gold Leaf 2: Cataquack to the skies"
GOLDLEAFSTAR3 = "Gold Leaf 3: When it Rains, it Pours"
GOLDLEAFSTAR4 = "Gold Leaf Comet: Cosmic Mario Forest Race"
GOLDLEAFSTAR6 = "Gold Leaf Secret: The Bell on the Big Trees"

SEASLIDESTAR1 = "Sea Slide 1: Going After Guppy"
SEASLIDESTAR2 = "Sea Slide 2: Faster Than a Speedrunning Penguin"
SEASLIDESTAR3 = "Sea Slide 3: The Silver Stars of Sea Slide"
SEASLIDESTAR4 = "Sea Slide Comet: Underwater Cosmic Mario Race"
SEASLIDESTAR6 = "Sea Slide Secret: Hurry, He's Hungry"

TOYTIMESTAR1 = "Toy Time 1: Heavy Metal Mecha Bowser"
TOYTIMESTAR2 = "Toy Time 2: Mario (or Luigi) Meets Mario"
TOYTIMESTAR3 = "Toy Time 3: Bouncing Down Cake Lane"
TOYTIMESTAR6 = "Toy Time Secret: The Flipswitch Chain"
TOYTIMESTAR4 = "Toy Time Comet: Fast Foes of Toy Time"

DEEPDARKSTAR1 = "Deep Dark 1: The Underground Ghost Ship"
DEEPDARKSTAR2 = "Deep Dark 2: Bubble Blastoff"
DEEPDARKSTAR3 = "Deep Dark 3: Guppy and the Underground Lake"
DEEPDARKSTAR4 = "Deep Dark Comet: Ghost Ship Daredevil Run"
DEEPDARKSTAR6 = "Deep Dark Secret: Boo in Box"

DREADNOUGHTSTAR1 = "Dreadnaught 1: Inflitrating the Dreadnought"
DREADNOUGHTSTAR2 = "Dreadnaught 2: Dreadnought's Colossal Cannons"
DREADNOUGHTSTAR3 = "Dreadnaught 3: Revenge of the Topman Tribe"
DREADNOUGHTSTAR4 = "Dreadnaught Comet: Topman Tribe Speed Run"
DREADNOUGHTSTAR6 = "Dreadnaught Secret: Dreadnought's Garbage Dump"

MELTYMOLTENSTAR1 = "Melty Molten 1: The Sinking Lava Spire"
MELTYMOLTENSTAR2 = "Melty Molten 2: Through the Meteor Storm"
MELTYMOLTENSTAR3 = "Melty Molten 3: Fiery Dino Piranha"
MELTYMOLTENSTAR4 = "Melty Molten Comet: Lava Spire Daredevil Run"
MELTYMOLTENSTAR6 = "Melty Molten Secret: Burning Tide"

SWEETSWEETSTAR = "Sweet Sweet: Rocky Road"
SLINGPODSTAR = "Sling Pod: A Very Sticky Situation"
DRIPDROPSTAR = "Drip Drop: Giant Eel Breakout"
BIGMOUTHSTAR = "Bigmouth: Bigmouth's Gold Bait"
SANDSPIRALSTAR = "Sandy Spiral: Choosing a Favorite Snack"
BOOSBONEYARDSTAR = "Boo's Boneyard: Racing the Spooky Speedster"
SNOWCAPSTAR = "Snow Cap: Star Bunnies in the Snow"

ROBOTREACTORSTAR1 = "Robot Reactor: Megaleg's Moon"
STARREACTORSTAR1 = "Star Reactor: The Fiery Stronghold"
AIRSHIPARMADASTAR1 = "Airship Armada: Sinking the Airships"
LAVAREACTORSTAR1 = "Lava Reactor: King Kaliente's Spicy Return"
DARKMATTERPLANTSTAR1 = "Dark Matter: Darkness on the Horizon"
GALAXYREACTORSTAR1 = "Galaxy Reactor: The Fate of the Universe"

TOYTIMESTAR5 = "Toy Time Purple Coins: Luigi's Purple Coins"
DREADNOUGHTSTAR5 = "Dreadnaught Purple Coins: Battlestation's Purple Coins"
MELTYMOLTENSTAR5 = "Melty Molten Purple Coins: Red-Hot Purple Coins"
DEEPDARKSTAR5 = "Deep Dark Purple Coins: Plunder the Purple Coins"
SEASLIDESTAR5 = "Sea Slide Purple Coins: Purple Coins by the Seaside"
GATEWAYSTAR2 = "Gateway Purple Coins: Gateway's Purple coins"
BATTLEROCKSTAR5 = "Battle Rock Purple Coins: Purple Coins on the Battlerock"
SPACEJUNKSTAR5 = "Space Junk Purple Coins: Purple Coin Spacewalk"
GUSTYGARDENSTAR5 = "Gusty Garden Purple Coins: Purple Coins on the Puzzle Cube"
BEACHBOWLSTAR5 = "Beach Bowl Purple Coins: Beachcombing for Purple Coins"
FREEZEFLAMESTAR5 = "Freezeflame Purple Coins: Purple Coins on the Summit"
GHOSTLYSTAR5 = "Ghostly Purple Coins: Purple Coins in the Bone Pen"
GOLDLEAFSTAR5 = "Gold Leaf Purple Coins: Purple Coins in the Woods"
DUSTYDUNESTAR5 = "Dusty Dune Purple Coins: Purple Coin in the Desert"