GOODEGGSTAR1 = "Good Egg 1: Dino Piranha"
GOODEGGSTAR2 = "Good Egg 2: A Snack of Cosmic Proportions"
GOODEGGSTAR3 = "Good Egg 3: King Kaliente's Battle Fleet"
GOODEGGSTAR4 = "Good Egg Comet: Dino Piranha Speed Run"
GOODEGGSTAR5 = "Good Egg Purple Coins: Purple Coin Omelet"
GOODEGGSTAR6 = "Good Egg Secret: Luigi on the Roof"

HONEYHIVESTAR1 = "Honeyhive: Bee Mario Takes Flight"
HONEYHIVESTAR2 = "Honeyhive: Trouble on the Tower"
HONEYHIVESTAR3 = "Honeyhive: Big Bad Bugaboom"
HONEYHIVESTAR4 = "Honeyhive: Honeyhive Cosmic Mario Race"
HONEYHIVESTAR5 = "Honeyhive: The Honeyhive's Purple Coins"
HONEYHIVESTAR6 = "Honeyhive: Luigi in the Honeyhive Kingdom"

LOOPDEELOOPSTAR = "Loopdeeloop: Surfing 101"
FLIPSWITCHSTAR = "Flipswitch: Painting the Planet Yellow"
ROLLINGGREENSTAR = "Rolling Green: Rolling in the Clouds"
HURRYSCURRYSTAR = "Hurry-Scurry: Shrinking Satellite"
BUBBLEBREEZESTAR = "Bubble Breeze: Through the Poison Swamp"
HONEYCLIMBSTAR = "Honeyclimb: Scaling the Sticky Wall"
BUOYBASESTAR1 = "Buoy Base: The Floating Fortress"
BUOYBASESTAR2 = "Buoy Base Secret: The Secret of Buoy Base"
GATEWAYSTAR1 = "Gateway: Grand Star Rescue"
BONEFINSTAR = "Bonefin: Kingfin's Fearsome Waters"
MATTERSPLATTERSTAR = "Matter Splatter: Watch Your Step"
ROLLINGGIZMOSTAR = "Rolling Gizmo: Gizmos, Gears, and Gadgets"
LOOPDEESWOOPSTAR = "Loopdeeswoop: The Galaxy's Greatest Wave"
BUBBLEBLASTSTAR = "Bubble Blast: The Electric Labyrinth"