# Origin Region
SHIP = "Comet Observatory"

# Hub Regions
TERRACE = "Dome 1"
FOUNTAIN = "Dome 2"
GARDEN = "Dome 6"
ENGINE = "Dome 5"
BEDROOM = "Dome 4"
KITCHEN = "Dome 3"
TRIALS = "Trials Planetoid"
LIBRARY = "Library"
COTU = "Center of the Universe"

# Hungry Luma/Special Galaxies - 12
GATEWAY = "Gateway Galaxy"
SWEETSWEET = "Sweet Sweet Galaxy"
SLINGPOD = "Sling Pod Galaxy"
DRIPDROP = "Drip Drop Galaxy"
BIGMOUTH = "Bigmouth Galaxy"
SANDSPIRAL = "Sand Spiral Galaxy"
SNOWCAP = "Snow Cap Galaxy"
BOOBONE = "Boo's Boneyard Galaxy"
ROLLINGGIZ = "Rolling Gizmo Galaxy"
LOOPDEESWOOP = "Loopdeeswoop Galaxy"
BUBBLEBLAST = "Bubble Blast Galaxy"
FINALE = "Grand Finale Galaxy"

# Boss Galaxies - 5 + goal
BOWJR1 = "Bowser Jr.'s Robot Reactor"
BOWJR2 = "Bowser Jr.'s Airship Armada"
BOWJR3 = "Bowser Jr.'s Lava Reactor"
BOWSER1 = "Bowser's Star Reactor"
BOWSER2 = "Bowser's Dark Matter Plant"
BOWSER3 = "Bowser's Galaxy Reactor"

# Major Galaxies - 15
GOODEGG = "Good Egg Galaxy"
HONEYHIVE = "Honeyhive Galaxy"
SPACEJUNK = "Space Junk Galaxy"
BATTLEROCK = "Battlerock Galaxy"
BEACHBOWL = "Beach Bowl Galaxy"
GHOSTLY = "Ghostly Galaxy"
GUSTY = "Gusty Garden Galaxy"
FREEZEFLAME = "Freezeflame Galaxy"
DUSTY = 'Dusty Dune Galaxy'
GOLDLEAF = "Gold Leaf Galaxy"
SEASLIDE = "Sea Slide Galaxy"
TOYTIME = "Toy Time Galaxy"
DEEPDARK = "Deep Dark Galaxy"
DREADNOUGHT = "Dreadnought Galaxy"
MELTY = "Melty Molten Galaxy"

# Minor Galaxies - 9
LOOPDEELOOP = "Loopdeeloop Galaxy"
FLIPSWITCH = "Flipswitch Galaxy"
ROLLINGGREEN = "Rolling Green Galaxy"
HURRYSCUR = "Hurry-Scurry Galaxy"
BUBBLEBREEZE = "Bubble Breeze Galaxy"
BUOY = "Buoy Base Galaxy"
HONEYCLIMB = "Honeyclimb Galaxy"
BONEFIN = "Bonefin Galaxy"
MATTER = "Matter Splatter Galaxy"

# Planetoid Subregions
## Gateway Galaxy
GATEWAY1HOMEP = "Gateway: Home Planet"
GATEWAY1HOLEY = "Gateway: Holey Planet"
GATEWAY1SMLTU = "Gateway: Small Tuning Shard Planet"
GATEWAY1LRGTU = "Gateway: Large Tuning Shard Planet"
GATEWAY1LRGTI = "Gateway: Large Tuning Planet Inside"
GATEWAY2HOMEP = "Gateway Comet: Home Planet"

## Terrace Galaxies
### Good Egg
GOODEGG1HOTOW = "Good Egg 1: House-Tower Planet"
GOODEGG1HOTOP = "Good Egg 1: Top of House"
GOODEGG1TONOT = "Good Egg 1: Tower Note Room"
GOODEGG1DUMBB = "Good Egg 1: Dumbbell Boulder Planet"
GOODEGG1SMLGR = "Good Egg 1: Small Grass Planet"
GOODEGG1BOULD = "Good Egg 1: Boulder Black Hole Planet"
GOODEGG1PANEL = "Good Egg 1: Flipswitch Platform"
GOODEGG1GRASS = "Good Egg 1: Grass Climb Planet"
GOODEGG1DINOP = "Good Egg 1: Dino Piranha Planet"
GOODEGG2HOTOW = "Good Egg 2: House-Tower Planet"
GOODEGG2HOTOP = "Good Egg 2: Top of House"
GOODEGG2TONOT = "Good Egg 2: Tower Note Room"
GOODEGG2PEARP = "Good Egg 2: Pear-shaped Planet"
GOODEGG2ROCKY = "Good Egg 2: Rocky Planet"
GOODEGG2YOSHI = "Good Egg 2: Yoshi Egg Planet"
GOODEGG2TOWER = "Good Egg 2: Hungry Luma Hill Planet"
GOODEGG2CAPSU = "Good Egg 2: Glass Capsule Planet"
GOODEGG2CAPSI = "Good Egg 2: Inside Glass Capsule"
GOODEGG2STARP = "Good Egg 2: Star Platform"
GOODEGG3HOTOW = "Good Egg 3: House-Tower Planet"
GOODEGG3HOTOP = "Good Egg 3: Top of House"
GOODEGG3TONOT = "Good Egg 3: Tower Note Room"

GOODEGG4HOTOW = "Good Egg Comet: House-Tower Planet"
GOODEGG4HOTOP = "Good Egg Comet: Top of House"
GOODEGG4TONOT = "Good Egg Comet: Tower Note Room"
GOODEGG4DUMBB = "Good Egg Comet: Dumbbell Boulder Planet"
GOODEGG4SMLGR = "Good Egg Comet: Small Grass Planet"
GOODEGG4BOULD = "Good Egg Comet: Boulder Black Hole Planet"
GOODEGG4PANEL = "Good Egg Comet: Flipswitch Platform"
GOODEGG4GRASS = "Good Egg Comet: Grass Climb Planet"
GOODEGG4DINOP = "Good Egg Comet: Dino Piranha Planet"
GOODEGG5PEARP = "Good Egg Purple Coin: Pear-shaped Planet"
GOODEGG5ROCKY = "Good Egg Purple Coin: Rocky Planet"
GOODEGG5YOSHI = "Good Egg Purple Coin: Yoshi Egg Planet"
GOODEGG6LUIGI = "Good Egg Secret: Luigi House"