# Origin Region
SHIP = "Comet Observatory"

# Hub Regions
TERRACE = "Dome 1"
FOUNTAIN = "Dome 2"
GARDEN = "Dome 6"
ENGINE = "Dome 5"
BEDROOM = "Dome 4"
KITCHEN = "Dome 3"
TRIALS = "Trials Planetoid"
LIBRARY = "Library"
COTU = "Center of the Universe"

# Hungry Luma/Special Galaxies - 12
GATEWAY = "Gateway Galaxy"
SWEETSWEET = "Sweet Sweet Galaxy"
SLINGPOD = "Sling Pod Galaxy"
DRIPDROP = "Drip Drop Galaxy"
BIGMOUTH = "Bigmouth Galaxy"
SANDSPIRAL = "Sand Spiral Galaxy"
SNOWCAP = "Snow Cap Galaxy"
BOOBONE = "Boo's Boneyard Galaxy"
ROLLINGGIZ = "Rolling Gizmo Galaxy"
LOOPDEESWOOP = "Loopdeeswoop Galaxy"
BUBBLEBLAST = "Bubble Blast Galaxy"
FINALE = "Grand Finale Galaxy"

# Boss Galaxies - 5 + goal
BOWJR1 = "Bowser Jr.'s Robot Reactor"
BOWJR2 = "Bowser Jr.'s Airship Armada"
BOWJR3 = "Bowser Jr.'s Lava Reactor"
BOWSER1 = "Bowser's Star Reactor"
BOWSER2 = "Bowser's Dark Matter Plant"
BOWSER3 = "Bowser's Galaxy Reactor"

# Major Galaxies - 15
GOODEGG = "Good Egg Galaxy"
HONEYHIVE = "Honeyhive Galaxy"
SPACEJUNK = "Space Junk Galaxy"
BATTLEROCK = "Battlerock Galaxy"
BEACHBOWL = "Beach Bowl Galaxy"
GHOSTLY = "Ghostly Galaxy"
GUSTY = "Gusty Garden Galaxy"
FREEZEFLAME = "Freezeflame Galaxy"
DUSTY = 'Dusty Dune Galaxy'
GOLDLEAF = "Gold Leaf Galaxy"
SEASLIDE = "Sea Slide Galaxy"
TOYTIME = "Toy Time Galaxy"
DEEPDARK = "Deep Dark Galaxy"
DREADNOUGHT = "Dreadnought Galaxy"
MELTY = "Melty Molten Galaxy"

# Minor Galaxies - 9
LOOPDEELOOP = "Loopdeeloop Galaxy"
FLIPSWITCH = "Flipswitch Galaxy"
ROLLINGGREEN = "Rolling Green Galaxy"
HURRYSCUR = "Hurry-Scurry Galaxy"
BUBBLEBREEZE = "Bubble Breeze Galaxy"
BUOY = "Buoy Base Galaxy"
HONEYCLIMB = "Honeyclimb Galaxy"
BONEFIN = "Bonefin Galaxy"
MATTER = "Matter Splatter Galaxy"

# Planetoid Subregions
## Gateway Galaxy
GATEWAY1HOMEP = "Gateway: Home Planet"
GATEWAY1HOLEY = "Gateway: Holey Planet"
GATEWAY1SMLTU = "Gateway: Small Tuning Shard Planet"
GATEWAY1LRGTU = "Gateway: Large Tuning Shard Planet"
GATEWAY1LRGTI = "Gateway: Large Tuning Planet Inside"
GATEWAY2HOMEP = "Gateway Comet: Home Planet"
SWEETSW1SWEET = "Sweet Sweet: Holey Platforms"

## Terrace Galaxies
### Good Egg
GOODEGG1HOTOW = "Good Egg 1: House-Tower Planet"
GOODEGG1HOTOP = "Good Egg 1: Top of House"
GOODEGG1TONOT = "Good Egg 1: Tower Note Room"
GOODEGG1DUMBB = "Good Egg 1: Dumbbell Boulder Planet"
GOODEGG1SMLGR = "Good Egg 1: Small Grass Planet"
GOODEGG1BOULD = "Good Egg 1: Boulder Black Hole Planet"
GOODEGG1PANEL = "Good Egg 1: Flipswitch Platform"
GOODEGG1GRASS = "Good Egg 1: Grass Climb Planet"
GOODEGG1DINOP = "Good Egg 1: Dino Piranha Planet"
GOODEGG2HOTOW = "Good Egg 2: House-Tower Planet"
GOODEGG2HOTOP = "Good Egg 2: Top of House"
GOODEGG2TONOT = "Good Egg 2: Tower Note Room"
GOODEGG2PEARP = "Good Egg 2: Pear-shaped Planet"
GOODEGG2ROCKY = "Good Egg 2: Rocky Planet"
GOODEGG2YOSHI = "Good Egg 2: Yoshi Egg Planet"
GOODEGG2TOWER = "Good Egg 2: Hungry Luma Hill Planet"
GOODEGG2CAPSU = "Good Egg 2: Glass Capsule Planet"
GOODEGG2CAPSI = "Good Egg 2: Inside Glass Capsule"
GOODEGG2STARP = "Good Egg 2: Star Platform"
GOODEGG3HOTOW = "Good Egg 3: House-Tower Planet"
GOODEGG3HOTOP = "Good Egg 3: Top of House"
GOODEGG3TONOT = "Good Egg 3: Tower Note Room"
GOODEGG3PALMT = "Good Egg 3: Palm Tree Planet"
GOODEGG3SANDY = "Good Egg 3: Sandy Planet"
GOODEGG3CHOMP = "Good Egg 3: Chain Chomp Meteor"
GOODEGG3CHOMI = "Good Egg 3: Chomp Meteor Interior"
GOODEGG3GRASS = "Good Egg 3: Grassy Meteor UFO"
GOODEGG3SHIPS = "Good Egg 3: Ship Pair"
GOODEGG3KBOSS = "Good Egg 3: King Kaliente's UFO"
GOODEGG4HOTOW = "Good Egg Comet: House-Tower Planet"
GOODEGG4HOTOP = "Good Egg Comet: Top of House"
GOODEGG4TONOT = "Good Egg Comet: Tower Note Room"
GOODEGG4DUMBB = "Good Egg Comet: Dumbbell Boulder Planet"
GOODEGG4SMLGR = "Good Egg Comet: Small Grass Planet"
GOODEGG4BOULD = "Good Egg Comet: Boulder Black Hole Planet"
GOODEGG4PANEL = "Good Egg Comet: Flipswitch Platform"
GOODEGG4GRASS = "Good Egg Comet: Grass Climb Planet"
GOODEGG4DINOP = "Good Egg Comet: Dino Piranha Planet"
GOODEGG5PEARP = "Good Egg Purple Coin: Pear-shaped Planet"
GOODEGG5ROCKY = "Good Egg Purple Coin: Rocky Planet"
GOODEGG5YOSHI = "Good Egg Purple Coin: Yoshi Egg Planet"
GOODEGG6LUIGI = "Good Egg Secret: Luigi House"

### Honeyhive
HONEYHI1LANDI = "Honeyhive 1: Landing Area"
HONEYHI1SIDEP = "Honeyhive 1: Small Side Pond"
HONEYHI1SMLHI = "Honeyhive 1: Small Hill"
HONEYHI1BOULR = "Honeyhive 1: Boulder Room"
HONEYHI1FOUNC = "Honeyhive 1: Small Fountain Cliff"
HONEYHI1WATRP = "Honeyhive 1: Waterfall Platform"
HONEYHI1WATRT = "Honeyhive 1: Waterfall Tunnel"
HONEYHI1BIGTR = "Honeyhive 1: Beneath the Big Tree"
HONEYHI1POUND = "Honeyhive 1: Tiny Tree Cliff"
HONEYHI1UNDER = "Honeyhive 1: Beneath the Kingdom Cliff"
HONEYHI1GARDN = "Honeyhive 1: Flower Garden"
HONEYHI1HONYC = "Honeyhive 1: Honeycomb Wall"
HONEYHI1PONDT = "Honeyhive 1: Queen Bee Pond"
HONEYHI1TREET = "Honeyhive 1: Treetop Platform"
HONEYHI2LANDI = "Honeyhive 2: Landing Area"
HONEYHI2SIDEP = "Honeyhive 2: Small Side Pond"
HONEYHI2SMLHI = "Honeyhive 2: Small Hill"
HONEYHI2FOUNC = "Honeyhive 2: Small Fountain Cliff"
HONEYHI2WATRP = "Honeyhive 2: Waterfall Platform"
HONEYHI2WATRT = "Honeyhive 2: Waterfall Tunnel"
HONEYHI2UNDER = "Honeyhive 2: Beneath the Kingdom Cliff"
HONEYHI2BIGTR = "Honeyhive 2: Beneath the Big Tree"
HONEYHI2POUND = "Honeyhive 2: Tiny Tree Cliff"
HONEYHI2CLIFF = "Honeyhive 2: Clifftop"
HONEYHI2HATS2 = "Honeyhive 2: Hat Planets"
HONEYHI2DROPL = "Honeyhive 2: Log Planet"
HONEYHI2TOWRB = "Honeyhive 2: Tower Base"
HONEYHI2TOWRM = "Honeyhive 2: Tower Middle"
HONEYHI2TOWRT = "Honeyhive 2: Tower Top"
HONEYHI3LANDI = "Honeyhive 3: Landing Area"
HONEYHI3SIDEP = "Honeyhive 3: Small Side Pond"
HONEYHI3SMLHI = "Honeyhive 3: Small Hill"
HONEYHI3BOULR = "Honeyhive 3: Boulder Room"
HONEYHI3FOUNC = "Honeyhive 3: Small Fountain Cliff"
HONEYHI3WATRP = "Honeyhive 3: Waterfall Platform"
HONEYHI3WATRT = "Honeyhive 3: Waterfall Tunnel"
HONEYHI3BIGTR = "Honeyhive 3: Beneath the Big Tree"
HONEYHI3POUND = "Honeyhive 3: Tiny Tree Cliff"
HONEYHI3UNDER = "Honeyhive 3: Beneath the Kingdom Cliff"
HONEYHI3BUGLA = "Honeyhive 3: Bugaboom Landing"
HONEYHI3BUGAB = "Honeyhive 3: Bugaboom Arena"
HONEYHI4LANDI = "Honeyhive Comet: Landing Area"
HONEYHI4WATRP = "Honeyhive Comet: Waterfall Platform"
HONEYHI4WATRT = "Honeyhive Comet: Waterfall Tunnel"
HONEYHI4UNDER = "Honeyhive Comet: Beneath the Kingdom Cliff"
HONEYHI5LANDI = "Honeyhive Purple Coin: Landing Area"
HONEYHI5SIDEP = "Honeyhive Purple Coin: Small Side Pond"
HONEYHI5SMLHI = "Honeyhive Purple Coin: Small Hill"
HONEYHI5FOUNC = "Honeyhive Purple Coin: Small Fountain Cliff"
HONEYHI5WATRP = "Honeyhive Purple Coin: Waterfall Platform"
HONEYHI5WATRT = "Honeyhive Purple Coin: Waterfall Tunnel"
HONEYHI5UNDER = "Honeyhive Purple Coin: Beneath the Kingdom Cliff"
HONEYHI5BIGTR = "Honeyhive Purple Coin: Beneath the Big Tree"
HONEYHI5POUND = "Honeyhive Purple Coin: Tiny Tree Cliff"
HONEYHI5CLIFF = "Honeyhive Purple Coin: Clifftop"
HONEYHI6LUIGI = "Honeyhive Secret: Luigi up a Tree"

### Minor Galaxies
LOOPDLO1ENTRY = "Loopdeeloop: Course Entryway"
LOOPDLO1COURS = "Loopdeeloop: Surfing Course"
FLIPSWI1PANEL = "Flipswitch: Panel Half Cube"
ROBOTRE1CAGEB = "Robot Reactor: Cage Break Planet"
ROBOTRE1MEGAL = "Robot Reactor: Megaleg's Moon"