# Origin Region
SHIP = "Comet Observatory"

# Hub Regions
TERRACE = "Dome 1"
FOUNTAIN = "Dome 2"
GARDEN = "Dome 6"
ENGINE = "Dome 5"
BEDROOM = "Dome 4"
KITCHEN = "Dome 3"
TRIALS = "Trials Planetoid"
LIBRARY = "Library"
COTU = "Center of the Universe"

# Hungry Luma/Special Galaxies - 12
GATEWAY = "Gateway Galaxy"
SWEETSWEET = "Sweet Sweet Galaxy"
SLINGPOD = "Sling Pod Galaxy"
DRIPDROP = "Drip Drop Galaxy"
BIGMOUTH = "Bigmouth Galaxy"
SANDSPIRAL = "Sand Spiral Galaxy"
SNOWCAP = "Snow Cap Galaxy"
BOOBONE = "Boo's Boneyard Galaxy"
ROLLINGGIZ = "Rolling Gizmo Galaxy"
LOOPDEESWOOP = "Loopdeeswoop Galaxy"
BUBBLEBLAST = "Bubble Blast Galaxy"
FINALE = "Grand Finale Galaxy"

# Boss Galaxies - 5 + goal
BOWJR1 = "Bowser Jr.'s Robot Reactor"
BOWJR2 = "Bowser Jr.'s Airship Armada"
BOWJR3 = "Bowser Jr.'s Lava Reactor"
BOWSER1 = "Bowser's Star Reactor"
BOWSER2 = "Bowser's Dark Matter Plant"
BOWSER3 = "Bowser's Galaxy Reactor"

# Major Galaxies - 15
GOODEGG = "Good Egg Galaxy"
HONEYHIVE = "Honeyhive Galaxy"
SPACEJUNK = "Space Junk Galaxy"
BATTLEROCK = "Battlerock Galaxy"
BEACHBOWL = "Beach Bowl Galaxy"
GHOSTLY = "Ghostly Galaxy"
GUSTY = "Gusty Garden Galaxy"
FREEZEFLAME = "Freezeflame Galaxy"
DUSTY = 'Dusty Dune Galaxy'
GOLDLEAF = "Gold Leaf Galaxy"
SEASLIDE = "Sea Slide Galaxy"
TOYTIME = "Toy Time Galaxy"
DEEPDARK = "Deep Dark Galaxy"
DREADNOUGHT = "Dreadnought Galaxy"
MELTY = "Melty Molten Galaxy"

# Minor Galaxies - 9
LOOPDEELOOP = "Loopdeeloop Galaxy"
FLIPSWITCH = "Flipswitch Galaxy"
ROLLINGGREEN = "Rolling Green Galaxy"
HURRYSCUR = "Hurry-Scurry Galaxy"
BUBBLEBREEZE = "Bubble Breeze Galaxy"
BUOY = "Buoy Base Galaxy"
HONEYCLIMB = "Honeyclimb Galaxy"
BONEFIN = "Bonefin Galaxy"
MATTER = "Matter Splatter Galaxy"

# Planetoid Subregions
## Gateway Galaxy
GATEWAY1HOMEP = "Gateway: Home Planet"
GATEWAY1HOLEY = "Gateway: Holey Planet"
GATEWAY1SMLTU = "Gateway: Small Tuning Shard Planet"
GATEWAY1LRGTU = "Gateway: Large Tuning Shard Planet"
GATEWAY1LRGTI = "Gateway: Large Tuning Planet Inside"
GATEWAY2HOMEP = "Gateway Comet: Home Planet"

## Observatory Specials
SWEETSW1SWEET = "Sweet Sweet: Holey Platforms"
SLINGPO1WEBPU = "Sling Pod Galaxy: Sling Pod Obstacle Course"
DRIPDRO1WATER = "Drip Drop: Water Planet"
BIGMOUT1ENTRY = "Bigmouth: Open Mouth"
BIGMOUT1THROA = "Bigmouth: Throat"
BIGMOUT1LOWER = "Bigmouth: Lower Stomach"
BIGMOUT1UPPER = "Bigmouth: Upper Stomach"
SANDSPI1SHIPB = "Sand Spiral: Ship's Bow"
SANDSPI1SANDT = "Sand Spiral: Sand Tunnel"
SANDSPI1SPIRA = "Sand Spiral: Rocky Spiral"
SNOWCAP1GLASS = "Snow Cap: Glass Sphere"
SNOWCAP1SNOWY = "Snow Cap: Snowman Planet"
BOOBONE1SKULL = "Boo's Boneyard: Skull Planet"
BOOBONE1PIT = "Boo's Boneyard: Boo Obstacle Course"
GALREAC1LANDI = "Galaxy Reactor: Landing"
GALREAC1WALLS = "Galaxy Reactor: Castle Wall"
GALREAC1SMSUN = "Galaxy Reactor: Orange Star"
GALREAC1BLSUN = "Galaxy Reactor: Blue Star"
GALREAC1SANDY = "Galaxy Reactor: Sandy Planet"
GALREAC1GRAVI = "Galaxy Reactor: Gravity Wall"
GALREAC1LAVAT = "Galaxy Reactor: Lava Tunnel"
GALREAC1STAIR = "Galaxy Reactor: Boss Stairs"
GALREAC1BOSS = "Galaxy Reactor: Bowser Arena"

## Trials Planetoids
ROLLGIZ1LANDI = "Rolling Gizmo: Landing Platform"
ROLLGIZ1MAINA = "Rolling Gizmo: Gears, Ramps & Dice"
LOOPSWO1LANDI = "Loopdeeswoop: Landing Platform"
LOOPSWO1TERR1 = "Loopdeeswoop: First Terrace"
LOOPSWO1TERR2 = "Loopdeeswoop: Second Terrace"
LOOPSWO1SWOOP = "Loopdeeswoop: Surfing Course"
BUBBLAS1LSTARP = "Bubble Blast: Landing Star Platform"
BUBBLAS1LNORTH = "Bubble Blast: North Fence Section"
BUBBLAS1LNORTW = "Bubble Blast: Northwest Fence Section"
BUBBLAS1LNORTE = "Bubble Blast: Northeast Fence Section"
BUBBLAS1LSOUTE = "Bubble Blast: Southeast Fence Section"
BUBBLAS1LSOUTW = "Bubble Blast: Southwest Fence Section"
BUBBLAS1LLONGF = "Bubble Blast: Electric Corridor"
GRANDFINALE = "Grand Finale: The Star Festival"

## Terrace Galaxies
### Good Egg
GOODEGG1HOTOW = "Good Egg 1: House-Tower Planet"
GOODEGG1HOTOP = "Good Egg 1: Top of House"
GOODEGG1TONOT = "Good Egg 1: Tower Note Room"
GOODEGG1DUMBB = "Good Egg 1: Dumbbell Boulder Planet"
GOODEGG1SMLGR = "Good Egg 1: Small Grass Planet"
GOODEGG1BOULD = "Good Egg 1: Boulder Black Hole Planet"
GOODEGG1PANEL = "Good Egg 1: Flipswitch Platform"
GOODEGG1GRASS = "Good Egg 1: Grass Climb Planet"
GOODEGG1DINOP = "Good Egg 1: Dino Piranha Planet"
GOODEGG2HOTOW = "Good Egg 2: House-Tower Planet"
GOODEGG2HOTOP = "Good Egg 2: Top of House"
GOODEGG2TONOT = "Good Egg 2: Tower Note Room"
GOODEGG2PEARP = "Good Egg 2: Pear-shaped Planet"
GOODEGG2ROCKY = "Good Egg 2: Rocky Planet"
GOODEGG2YOSHI = "Good Egg 2: Yoshi Egg Planet"
GOODEGG2TOWER = "Good Egg 2: Hungry Luma Hill Planet"
GOODEGG2CAPSU = "Good Egg 2: Glass Capsule Planet"
GOODEGG2CAPSI = "Good Egg 2: Inside Glass Capsule"
GOODEGG2STARP = "Good Egg 2: Star Platform"
GOODEGG3HOTOW = "Good Egg 3: House-Tower Planet"
GOODEGG3HOTOP = "Good Egg 3: Top of House"
GOODEGG3TONOT = "Good Egg 3: Tower Note Room"
GOODEGG3PALMT = "Good Egg 3: Palm Tree Planet"
GOODEGG3SANDY = "Good Egg 3: Sandy Planet"
GOODEGG3CHOMP = "Good Egg 3: Chain Chomp Meteor"
GOODEGG3CHOMI = "Good Egg 3: Chomp Meteor Interior"
GOODEGG3GRASS = "Good Egg 3: Grassy Meteor UFO"
GOODEGG3SHIPS = "Good Egg 3: Ship Pair"
GOODEGG3KBOSS = "Good Egg 3: King Kaliente's UFO"
GOODEGG4HOTOW = "Good Egg Comet: House-Tower Planet"
GOODEGG4HOTOP = "Good Egg Comet: Top of House"
GOODEGG4TONOT = "Good Egg Comet: Tower Note Room"
GOODEGG4DUMBB = "Good Egg Comet: Dumbbell Boulder Planet"
GOODEGG4SMLGR = "Good Egg Comet: Small Grass Planet"
GOODEGG4BOULD = "Good Egg Comet: Boulder Black Hole Planet"
GOODEGG4PANEL = "Good Egg Comet: Flipswitch Platform"
GOODEGG4GRASS = "Good Egg Comet: Grass Climb Planet"
GOODEGG4DINOP = "Good Egg Comet: Dino Piranha Planet"
GOODEGG5PEARP = "Good Egg Purple Coin: Pear-shaped Planet"
GOODEGG5ROCKY = "Good Egg Purple Coin: Rocky Planet"
GOODEGG5YOSHI = "Good Egg Purple Coin: Yoshi Egg Planet"
GOODEGG6LUIGI = "Good Egg Secret: Luigi House"

### Honeyhive
HONEYHI1LANDI = "Honeyhive 1: Landing Area"
HONEYHI1SIDEP = "Honeyhive 1: Small Side Pond"
HONEYHI1SMLHI = "Honeyhive 1: Small Hill"
HONEYHI1BOULR = "Honeyhive 1: Boulder Room"
HONEYHI1FOUNC = "Honeyhive 1: Small Fountain Cliff"
HONEYHI1WATRP = "Honeyhive 1: Waterfall Platform"
HONEYHI1WATRT = "Honeyhive 1: Waterfall Tunnel"
HONEYHI1BIGTR = "Honeyhive 1: Beneath the Big Tree"
HONEYHI1POUND = "Honeyhive 1: Tiny Tree Cliff"
HONEYHI1UNDER = "Honeyhive 1: Beneath the Kingdom Cliff"
HONEYHI1GARDN = "Honeyhive 1: Flower Garden"
HONEYHI1HONYC = "Honeyhive 1: Honeycomb Wall"
HONEYHI1PONDT = "Honeyhive 1: Queen Bee Pond"
HONEYHI1TREET = "Honeyhive 1: Treetop Platform"
HONEYHI2LANDI = "Honeyhive 2: Landing Area"
HONEYHI2SIDEP = "Honeyhive 2: Small Side Pond"
HONEYHI2SMLHI = "Honeyhive 2: Small Hill"
HONEYHI2FOUNC = "Honeyhive 2: Small Fountain Cliff"
HONEYHI2WATRP = "Honeyhive 2: Waterfall Platform"
HONEYHI2WATRT = "Honeyhive 2: Waterfall Tunnel"
HONEYHI2UNDER = "Honeyhive 2: Beneath the Kingdom Cliff"
HONEYHI2BIGTR = "Honeyhive 2: Beneath the Big Tree"
HONEYHI2POUND = "Honeyhive 2: Tiny Tree Cliff"
HONEYHI2CLIFF = "Honeyhive 2: Clifftop"
HONEYHI2HATS2 = "Honeyhive 2: Hat Planets"
HONEYHI2DROPL = "Honeyhive 2: Log Planet"
HONEYHI2TOWRB = "Honeyhive 2: Tower Base"
HONEYHI2TOWRM = "Honeyhive 2: Tower Middle"
HONEYHI2TOWRT = "Honeyhive 2: Tower Top"
HONEYHI3LANDI = "Honeyhive 3: Landing Area"
HONEYHI3SIDEP = "Honeyhive 3: Small Side Pond"
HONEYHI3SMLHI = "Honeyhive 3: Small Hill"
HONEYHI3BOULR = "Honeyhive 3: Boulder Room"
HONEYHI3FOUNC = "Honeyhive 3: Small Fountain Cliff"
HONEYHI3WATRP = "Honeyhive 3: Waterfall Platform"
HONEYHI3WATRT = "Honeyhive 3: Waterfall Tunnel"
HONEYHI3BIGTR = "Honeyhive 3: Beneath the Big Tree"
HONEYHI3POUND = "Honeyhive 3: Tiny Tree Cliff"
HONEYHI3UNDER = "Honeyhive 3: Beneath the Kingdom Cliff"
HONEYHI3BUGLA = "Honeyhive 3: Bugaboom Landing"
HONEYHI3BUGAB = "Honeyhive 3: Bugaboom Arena"
HONEYHI4LANDI = "Honeyhive Comet: Landing Area"
HONEYHI4WATRP = "Honeyhive Comet: Waterfall Platform"
HONEYHI4WATRT = "Honeyhive Comet: Waterfall Tunnel"
HONEYHI4UNDER = "Honeyhive Comet: Beneath the Kingdom Cliff"
HONEYHI5LANDI = "Honeyhive Purple Coin: Landing Area"
HONEYHI5SIDEP = "Honeyhive Purple Coin: Small Side Pond"
HONEYHI5SMLHI = "Honeyhive Purple Coin: Small Hill"
HONEYHI5FOUNC = "Honeyhive Purple Coin: Small Fountain Cliff"
HONEYHI5WATRP = "Honeyhive Purple Coin: Waterfall Platform"
HONEYHI5WATRT = "Honeyhive Purple Coin: Waterfall Tunnel"
HONEYHI5UNDER = "Honeyhive Purple Coin: Beneath the Kingdom Cliff"
HONEYHI5BIGTR = "Honeyhive Purple Coin: Beneath the Big Tree"
HONEYHI5POUND = "Honeyhive Purple Coin: Tiny Tree Cliff"
HONEYHI5CLIFF = "Honeyhive Purple Coin: Clifftop"
HONEYHI6LUIGI = "Honeyhive Secret: Luigi up a Tree"

### Minor Galaxies
LOOPDLO1ENTRY = "Loopdeeloop: Course Entryway"
LOOPDLO1COURS = "Loopdeeloop: Surfing Course"
FLIPSWI1PANEL = "Flipswitch: Panel Half Cube"
ROBOTRE1CAGEB = "Robot Reactor: Cage Break Planet"
ROBOTRE1MEGAL = "Robot Reactor: Megaleg's Moon"

## Fountain Galaxies
### Space Junk
SPACJUN1LANDI = "Space Junk 1: Landing Platform"
SPACJUN1CRYCY = "Space Junk 1: Crystal Prism"
SPACJUN1SPHE3 = "Space Junk 1: Three Glass Spheres"
SPACJUN1HSHIP = "Space Junk 1: Hocotate Ship"
SPACJUN1TOADS = "Space Junk 1: Toadship Platform"
SPACJUN1SILVE = "Space Junk 1: Cosmic Platforms"
SPACJUN2TOADS = "Space Junk 2: Toadships"
SPACJUN2AIRS1 = "Space Junk 2: First Airship"
SPACJUN2AIRS2 = "Space Junk 2: Second Airship"
SPACJUN2AIRS3 = "Space Junk 2: Third Airship"
SPACJUN2AIRSI = "Space Junk 2: Inside Third Airship"
SPACJUN2BATTL = "Space Junk 2: Kamella's Battleship"
SPACJUN3TOADS = "Space Junk 3: Toadships"
SPACJUN3CRYCY = "Space Junk 3: Crystal Prism"
SPACJUN3GLASS = "Space Junk 3: Glass Covered Planet"
SPACJUN6YOSHI = "Space Junk 3: Yoshi Head Planet"
SPACJUN3FLOAT = "Space Junk 3: Floating Entrance"
SPACJUN3HSHIP = "Space Junk 3: Hocotate Ship"
SPACJUN3TARAN = "Space Junk 3: Tarantox's Web Arena"
SPACJUN4LANDI = "Space Junk Comet: Landing Platform"
SPACJUN4CRYCY = "Space Junk Comet: Crystal Prism"
SPACJUN4SPHE3 = "Space Junk Comet: Three Glass Spheres"
SPACJUN4HSHIP = "Space Junk Comet: Hocotate Ship"
SPACJUN4TOADS = "Space Junk Comet: Toadship Platform"
SPACJUN4SILVE = "Space Junk Comet: Cosmic Platforms"
SPACJUN5PURPL = "Space Junk Purple Coins: Cosmic Platforms"

### Battlerock
BATTLE1LANDI = "Battlerock 1: Landing Platforms"
BATTLE1SPINY = "Battlerock 1: Spiny UFO"
BATTLE1AUTOS = "Battlerock 1: Autoscroll Platform"
BATTLE1FINAL = "Battlerock 1: Caged Star Platforms"
BATTLE7LUIGI = "Battlerock Luigi: Luigi's Cage"
BATTLE5AUTOS = "Battlerock Purple Coins: Autoscroll Platform"
BATTLE2LANDI = "Battlerock 2: Landing Platforms"
BATTLE2TETRA = "Battlerock 2: Color Orbs Planet"
BATTLE2MINEF = "Battlerock 2: Pull Star Minefield"
BATTLE2CAGEO = "Battlerock 2: Battlerock Container Outside"
BATTLE2CAGEI = "Battlerock 2: Battlerock Container Inside"
BATTLE2PATCH = "Battlerock 2: Patchwork Cylinder"
BATTLE6BREAK = "Battlerock Secret: Breaker Platform"
BATTLE3LANDI = "Battlerock 3: Landing Platforms"
BATTLE3TRIPL = "Battlerock 3: Triple Platforms"
BATTLE3LUMAP = "Battlerock 3: Luma Platforms"
BATTLE3CLIFF = "Battlerock 3: Cliffside Platforms"
BATTLE3INSID = "Battlerock 3: Inside the Battlerock"
BATTLE3BCAGE = "Battlerock 3: Circular Room"
BATTLE3EXITG = "Battlerock 3: Battlerock Laser Door"
BATTLE3TOPMA = "Battlerock 3: Topmaniac's UFO"
BATTLE4TOPMA = "Battlerock Comet: Topmaniac's UFO"

### Dome Minors
ROLLGRESTART = "Rolling Green: Landing Platform"
ROLLGREBATTL = "Rolling Green: Goomba Battlefield"
ROLLGREFINIS = "Rolling Green: Goal Platform"
HURRSCULANDI = "Hurry-Scurry: Landing Platforms"
HURRSCUPLANE = "Hurry-Scurry: Disappearing Planet"
STARREALPIPE = "Star Reactor: Landing Pipe"
STAREAGRAVIT = "Star Reactor: Gravity Wall"
STAREASTAIRS = "Star Reactor: Stairs to Boss"
STAREABOSSAR = "Star Reactor: Reactor Planet"

## Kitchen
### Beach Bowl
BEACH1LANDI = "Beach Bowl 1: Beach Shore"
BEACH1LAKES = "Beach Bowl 1: Beach Bowl Lake"
BEACH1CLIFB = "Beach Bowl 1: Waterfall Cliff"
BEACH1CLIFT = "Beach Bowl 1: Top of Waterfall"
BEACH1BLOCK = "Beach Bowl 1: Block Bit Room"
BEACH2LANDI = "Beach Bowl 2: Beach Shore"
BEACH2LAKES = "Beach Bowl 2: Beach Bowl Lake"
BEACH2BLOCK = "Beach Bowl 2: Block Bit Room"
BEACH3LANDI = "Beach Bowl 3: Beach Shore"
BEACH3LAKES = "Beach Bowl 3: Beach Bowl Lake"
BEACH3CAVES = "Beach Bowl 3: Undersea Cavern"
BEACH3STCYC = "Beach Bowl 3: Stone Cyclone"
BEACH3BLOCK = "Beach Bowl 3: Block Bit Room"
BEACH4STCYC = "Beach Bowl Comet: Stone Cyclone"
BEACH5LANDI = "Beach Bowl Purple Coins: Beach Shore"
BEACH5LAKES = "Beach Bowl Purple Coins: Beach Bowl Lake"
BEACH5CLIFB = "Beach Bowl Purple Coins: Waterfall Cliff"
BEACH5CLIFT = "Beach Bowl Purple Coins: Top of Waterfall"
BEACH6WATRB = "Beach Bowl Secret: Waterfalls Base"
BEACH6ICELA = "Beach Bowl Secret: Icy Pond"

### Ghostly
GHOSTLY1TOADS = "Ghostly 1: Green Toadship"
GHOSTLY1ENTRY = "Ghostly 1: Spooky Gateway"
GHOSTLY1FOYER = "Ghostly 1: Mansion Foyer"
GHOSTLY1BLACK = "Ghostly 1: Black Hole Room"
GHOSTLY1LIBRA = "Ghostly 1: Secret Library"
GHOSTLY1BALCO = "Ghostly 1: Outer Balcony"
GHOSTLY1CORR1 = "Ghostly 1: Balcony Corridor"
GHOSTLY1CORR2 = "Ghostly 1: Booshroom Library"
GHOSTLY2TOADS = "Ghostly 2: Green Toadship"
GHOSTLY2ENTRY = "Ghostly 2: Spooky Gateway"
GHOSTLY2BOORA = "Ghostly 2: Boo Racecourse"
GHOSTLY6MATTE = "Ghostly Secret: Matter Splatter Corridors"
GHOSTLY3TOADS = "Ghostly 3: Green Toadship"
GHOSTLY3ENTRY = "Ghostly 3: Spooky Gateway"
GHOSTLY3FOYER = "Ghostly 3: Mansion Foyer"
GHOSTLY3SPIDE = "Ghostly 3: Spider Wall"
GHOSTLY3SLING = "Ghostly 3: Sling Pod Wall"
GHOSTLY3TRAMP = "Ghostly 3: Trampoline Planet"
GHOSTLY3BOSSA = "Ghostly 3: Bouldergeist Arena"
GHOSTLY4BOSSA = "Ghostly Comet: Bouldergeist Arena"
GHOSTLY5PCOIN = "Ghostly Purple Coins: Purple Coin Pen"