miniature_to_galaxy: dict = {"MiniEggStarGalaxy"         : "Good Egg Galaxy",
                             "MiniHoneyBeeKingdomGalaxy" : "Honeyhive Galaxy",
                             "MiniSurfingLv1Galaxy"      : "Loopdeeloop Galaxy",
                             "MiniFlipPanelExGalaxy"     : "Flipswitch Galaxy",
                             "MiniTriLegLv1Galaxy"       : "Bowser Jr.'s Robot Reactor",
                             "MiniStarDustGalaxy"        : "Space Junk Galaxy",
                             "MiniTamakoroExLv1Galaxy"   : "Rolling Green Galaxy",
                             "MiniBattleShipGalaxy"      : "Battlerock Galaxy",
                             "MiniBreakDownPlanetGalaxy" : "Hurry-Scurry Galaxy",
                             "MiniKoopaBattleVs1Galaxy"  : "Bowser's Star Reactor",
                             "MiniHeavenlyBeachGalaxy"   : "Beach Bowl Galaxy",
                             "MiniCubeBubbleExLv1Galaxy" : "Bubble Breeze Galaxy",
                             "MiniPhantomGalaxy"         : "Ghostly Galaxy",
                             "MiniOceanFloaterLandGalaxy": "Buoy Base Galaxy",
                             "MiniKoopaJrShipLv1Galaxy"  : "Bowser Jr.'s Airship Armada",
                             "MiniCosmosGardenGalaxy"    : "Gusty Garden Galaxy",
                             "MiniIceVolcanoGalaxy"      : "Freezeflame Galaxy",
                             "MiniHoneyBeeExGalaxy"      : "Honeyclimb Galaxy",
                             "MiniSandClockGalaxy"       : "Dusty Dune Galaxy",
                             "MiniKoopaBattleVs2Galaxy"  : "Bowser's Dark Matter Plant",
                             "MiniReverseKingdomGalaxy"  : "Gold Leaf Galaxy",
                             "MiniOceanRingGalaxy"       : "Sea Slide Galaxy",
                             "MiniSkullSharkGalaxy"      : "Bonefin Galaxy",
                             "MiniFactoryGalaxy"         : "Toy Time Galaxy",
                             "MiniFloaterOtaKingGalaxy"  : "Bowser Jr.'s Lava Reactor",
                             "MiniOceanPhantomCaveGalaxy": "Deep Dark Galaxy",
                             "MiniCannonFleetGalaxy"     : "Dreadnought Galaxy",
                             "MiniDarkRoomGalaxy"        : "Matter Splatter Galaxy",
                             "MiniHellProminenceGalaxy"  : "Melty Molten Galaxy",
                             
                             "SurpBeltConveyerExGalaxy"  : "Sweet Sweet Galaxy",
                             "SurpCocoonExGalaxy"        : "Sling Pod Galaxy",
                             "SurpCubeBubbleExLv2Galaxy" : "Bubble Blast Galaxy",
                             "SurpFishTunnelGalaxy"      : "Bigmouth Galaxy",
                             "SurpPeachCastleFinalGalaxy": "Grand Finale Galaxy",
                             "SurpSnowCapsuleGalaxy"     : "Snow Cap Galaxy",
                             "SurpSurfingLv2Galaxy"      : "Loopdeeswoop Galaxy",
                             "SurpTamakoroExLv2Galaxy"   : "Rolling Gizmo Galaxy",
                             "SurpTearDropGalaxy"        : "Drip Drop Galaxy",
                             "SurpTeresaMario2DGalaxy"   : "Boo's Boneyard Galaxy",
                             "SurpTransformationExGalaxy": "Sand Spiral Galaxy",
                             
                             "AstroChildRoom"            : "Gateway Galaxy"}

galaxy_to_miniature: dict = {"Good Egg Galaxy"            : "MiniEggStarGalaxy",
                             "Honeyhive Galaxy"           : "MiniHoneyBeeKingdomGalaxy",
                             "Loopdeeloop Galaxy"         : "MiniSurfingLv1Galaxy",
                             "Flipswitch Galaxy"          : "MiniFlipPanelExGalaxy",
                             "Bowser Jr.'s Robot Reactor" : "MiniTriLegLv1Galaxy",
                             "Space Junk Galaxy"          : "MiniStarDustGalaxy",
                             "Rolling Green Galaxy"       : "MiniTamakoroExLv1Galaxy",
                             "Battlerock Galaxy"          : "MiniBattleShipGalaxy",
                             "Hurry-Scurry Galaxy"        : "MiniBreakDownPlanetGalaxy",
                             "Bowser's Star Reactor"      : "MiniKoopaBattleVs1Galaxy",
                             "Beach Bowl Galaxy"          : "MiniHeavenlyBeachGalaxy",
                             "Bubble Breeze Galaxy"       : "MiniCubeBubbleExLv1Galaxy",
                             "Ghostly Galaxy"             : "MiniPhantomGalaxy",
                             "Buoy Base Galaxy"           : "MiniOceanFloaterLandGalaxy",
                             "Bowser Jr.'s Airship Armada": "MiniKoopaJrShipLv1Galaxy",
                             "Gusty Garden Galaxy"        : "MiniCosmosGardenGalaxy",
                             "Freezeflame Galaxy"         : "MiniIceVolcanoGalaxy",
                             "Honeyclimb Galaxy"          : "MiniHoneyBeeExGalaxy",
                             "Dusty Dune Galaxy"          : "MiniSandClockGalaxy",
                             "Bowser's Dark Matter Plant" : "MiniKoopaBattleVs2Galaxy",
                             "Gold Leaf Galaxy"           : "MiniReverseKingdomGalaxy",
                             "Sea Slide Galaxy"           : "MiniOceanRingGalaxy",
                             "Bonefin Galaxy"             : "MiniSkullSharkGalaxy",
                             "Toy Time Galaxy"            : "MiniFactoryGalaxy",
                             "Bowser Jr.'s Lava Reactor"  : "MiniFloaterOtaKingGalaxy",
                             "Deep Dark Galaxy"           : "MiniOceanPhantomCaveGalaxy",
                             "Dreadnought Galaxy"         : "MiniCannonFleetGalaxy",
                             "Matter Splatter Galaxy"     : "MiniDarkRoomGalaxy",
                             "Melty Molten Galaxy"        : "MiniHellProminenceGalaxy",

                             "Sweet Sweet Galaxy"         : "SurpBeltConveyerExGalaxy",
                             "Sling Pod Galaxy"           : "SurpCocoonExGalaxy",
                             "Bubble Blast Galaxy"        : "SurpCubeBubbleExLv2Galaxy",
                             "Bigmouth Galaxy"            : "SurpFishTunnelGalaxy",
                             "Grand Finale Galaxy"        : "SurpPeachCastleFinalGalaxy",
                             "Snow Cap Galaxy"            : "SurpSnowCapsuleGalaxy",
                             "Loopdeeswoop Galaxy"        : "SurpSurfingLv2Galaxy",
                             "Rolling Gizmo Galaxy"       : "SurpTamakoroExLv2Galaxy",
                             "Drip Drop Galaxy"           : "SurpTearDropGalaxy",
                             "Boo's Boneyard Galaxy"      : "SurpTeresaMario2DGalaxy",
                             "Sand Spiral Galaxy"         : "SurpTransformationExGalaxy",
                             
                             "Gateway Galaxy"             : "AstroChildRoom"}